### ISSUE TITLE
Multi-image still borked in Telegram

### ISSUE THREAD

**Issue by dangeredwolf** [dangeredwolf/FixTweet#15]
Certain images, mainly multiple larger ones, just are refused to be embedded by Telegram while Discord is fine. We've temporarily disabled multi-image for Telegram until we can figure out how to fix this properly.

**Comment by Deer-Spangle** [comment]
Do you know the size of the images, perchance?
I'm not sure if the rules are the same for embedded pages as they are for sending an image, but [I found a while back](https://github.com/Deer-Spangle/FA-search-bot/blob/master/experiments/telegram_image_size.md) that the maximum width+height (or semiperimeter) of an image sent in Telegram is 10,000 pixels, and the maximum aspect ratio is 1:20

Not sure if this is helpful, or whether Telegram will follow the same rules for that (they're pretty arbitrary, unfortunately)

**Comment by dangeredwolf** [comment]
@Deer-Spangle I just noticed your comment. i'm not entirely sure, i thought we had a resolution cap less than that unless it's somehow not being applied so hm.

**Comment by ZornTaov** [comment]
I just came across one multi image tweet that pxtwitter cut off the side of one of the images in telegram https://pxtwitter.com/yardleyart/status/1494236450979782660?s=20&t=1hjnTr3AyAQYcvjDEyq4yQ posting this here as it is somewhat related. 
![image](https://user-images.githubusercontent.com/2144351/184437465-81755682-c898-4efe-955a-dbe702c56b6a.png)

**Comment by dangeredwolf** [comment]
This was a miscalculation in how resizing works but it's since been fixed. @ZornTaov 

I'll go ahead and close this issue unless we find some other case where this breaks

**Comment by rugk** [comment]
So any news here? This is linked from the readme but I don't quite see the state here, is tgat feature still disabled?

Also if it only breaks telegram may you do UA detections and only disable it for telegram maybe?
