### ISSUE TITLE
Video Embed doesn't work for Quote Retweets in discord

### ISSUE THREAD

**Issue by mikabre** [dangeredwolf/FixTweet#17]
fxtwitter embeds video as a static image in quote retweets.

Default twitter embed:
![image](https://user-images.githubusercontent.com/5118242/182507968-27a3a01a-8c82-4f97-b000-587511be4876.png)

fxtwitter embed:
![image](https://user-images.githubusercontent.com/5118242/182508010-bdfcad63-fbd7-4462-8da8-bbee1bfddb44.png)

**Comment by dangeredwolf** [comment]
Ah I see what happened, when I rewrote the code to handle this (in separating API from embed code) it mistakenly assumed the card type as `summary_large_image` for some reason which is for images instead of surfacing the card type from the quote tweet (which if containing a video should be player).

**Comment by dangeredwolf** [comment]
<img width="518" alt="Screenshot 2022-08-03 at 18 57 21" src="https://user-images.githubusercontent.com/2636265/182726585-f23df604-ddce-48c4-8f70-bc6e0892d312.png">

**Comment by mskacelik** [comment]
> <img alt="Screenshot 2022-08-03 at 18 57 21" width="518" src="https://user-images.githubusercontent.com/2636265/182726585-f23df604-ddce-48c4-8f70-bc6e0892d312.png">
Is it possible to add **Quoting ↘️** string into the video embed.
Something like this:
```
{text of the quote retweet}
`Quoting ↘️ {author of quoted tweet}`
{text of the quoted tweet}
{video}
```

**Comment by dangeredwolf** [comment]
@mskacelik Unfortunately, on Discord this is impossible due to the way Discord embeds videos from websites. It does however work on Telegram.
<img width="237" alt="Screenshot 2023-05-11 at 14 49 19" src="https://github.com/FixTweet/FixTweet/assets/2636265/1f00dd79-3b67-492f-99b7-287a349b7c97">
