### ISSUE TITLE
Multi-image direct link gets wrong image

### ISSUE THREAD

**Issue by TrueHitoare** [dangeredwolf/FixTweet#23]
Using the `https://d.twittpr.com/dangeredwolf/status/1547514042146865153/photo/3`-style link (or any other formatting with the same functionality) gives the wrong image. Specifically, it gives the image one further into the post than requested (looping around to the start if you go past the end). The example link gives the fourth image in the post, where a plain Twitter link would give the third image.

As `/photo/0` gives the first image, this seems to be a simple off-by-one error, where Twitter uses 1-indexing for their links and the FixTweet system uses 0-indexing.

**Comment by dangeredwolf** [comment]
oh shoot! you're right, that is broken specifically for direct media links, let me find the offending code and fix that right up

**Comment by dangeredwolf** [comment]
Yep that was basically a 1-line fix, thanks for telling me about it!

**Comment by dangeredwolf** [comment]
I rewrote a lot of FixTweet's underlying code when developing the API and while it overall went smoothly there were a couple edge cases I hadn't fully tested for, so I appreciate you helping me out by reporting it. If you have any other issues please feel free to open another issue!
