### ISSUE TITLE
Missing stats for nerds in /version

### ISSUE THREAD

**Issue by sparkyfen** [dangeredwolf/FixTweet#67]
I saw that the stats are available in the`<head>` tag but they are missing in the body when the page is rendered.

Prob just needs a quick copy-paste.
https://github.com/dangeredwolf/FixTweet/blob/8d59ff240e7e6905d427779d1047774e884e02d4/src/strings.ts#L119

**Comment by dangeredwolf** [comment]
We don't include IP address info in the body because imo it's not very relevant for end users and more relevant to seeing where a crawler is requesting FixTweet from.

**Comment by sparkyfen** [comment]
Sorry if you've indirectly answered this but can't the end user see it in the meta tag anyways? Is the goal to prevent them from seeing it? Or just for crawlers?

**Comment by dangeredwolf** [comment]
If a user is savvy enough to know how to use inspect element or other tools to find the meta tag they're savvy enough to know what an IP address is so I don't see their being any issue there.

The reason we do it for crawlers is I find it neat to look at the IP address of which server Discord or Telegram is using to calculate the embed.

**Comment by dangeredwolf** [comment]
If you have any other concerns you can reopen the issue

**Comment by sparkyfen** [comment]
I guess then my final question is, isn't this <h3> tag useless then? https://github.com/dangeredwolf/FixTweet/blob/main/src/strings.ts#L119

**Comment by dangeredwolf** [comment]
it's separate for styling reasons lol
