### ISSUE TITLE
Your twitter account does not exist anymore

### ISSUE THREAD

**Issue by rugk** [dangeredwolf/FixTweet#88]
Hi
https://twitter.com/dangeredwolf is linked in the Readme at the end, but that leads to a 404/"account does not exist".

So it seems you deleted it.

**Comment by dangeredwolf** [comment]
I temp deactivated due to harassment issues with a transphobe.

**Comment by Puppercino** [comment]
> I temp deactivated due to harassment issues with a transphobe.

Dangeredwolf, I am sorry to hear that you have been a target of harassment by transphobes. It is truly disappointing that there are people who use this situation to vilify and demean with transphobia. However, this does not absolve you from what you have done, and it's pretty messed up that you continue to downplay.

> Hi https://twitter.com/dangeredwolf is linked in the Readme at the end, but that leads to a 404/"account does not exist".
> 
> So it seems you deleted it.

Personally, I usually don't go out of my way to insert myself into these situations, especially when people continue to get hurt by it, but for transparancy's sake, it's important to provide information when it's needed, and I think this is one of those cases. **Dangeredwolf was recently alleged to have groomed users when they were underage and then be publicly dishonest (despite admitting it previously) about what has occurred.** 

Here is the document detailing the events that have occurred, please be warned that this contains disturbing material: [Google Doc Link](https://docs.google.com/document/d/1SQoVFVx7C_gduAv9Z0SFSF0hke4uK5ZkhFnktPva4zs/edit)

**Comment by Puppercino** [comment]
This page has been archived on the wayback machine, it can be viewed [here](https://web.archive.org/web/20221006050321/https://github.com/dangeredwolf/FixTweet/issues/88). 
URL: https://web.archive.org/web/20221006050321/https://github.com/dangeredwolf/FixTweet/issues/88
